### ISSUE TITLE
绷不住了，二十多分钟过去了，没见到第三关

### ISSUE THREAD

**Issue by leck995** [leewyatt/FXGL_Mario#1]
愤怒改了100条命，可第二关开关方式我还是接受不了，怎么都够不到（吐槽的时候想起来可以二级跳了），呜呜

**Comment by leewyatt** [comment]
https://youtu.be/74vMoiGLzyk 这是我的通关录像啊 , 还算简单吧, 你需要跳到下面有弹簧的地方, 然后就能够到了

**Comment by leewyatt** [comment]
> 愤怒改了100条命，可第二关开关方式我还是接受不了，怎么都够不到（吐槽的时候想起来可以二级跳了），呜呜

怎么样, 现在通关了吗?   我就续写了你开始玩的两关, 后面的5关, 是原作者写的 ,我觉得太简单了,  玩法也少, 就新增了两关.

**Comment by leck995** [comment]
84条命过的，第一关熟练到不带停的。主要是第二关，经常忘了二级跳，中间那个地刺我起码死了8次，太不明显了，老是以为是安全地带，还有就是边角容易卡住，虽然可以跳出去。
